schema_version: v0.0.1

application:
  name: wordpress-app
  description: WordPress is a free and open-source content management system
  appConfig:
    version: 1
  artifacts:
    - name: wordpress_container_image
      id: 1435bc98-bea6-11eb-8529-0242ac130003
      containerImage:
        provider: dockerhub_container_registry
        host: index.docker.io
        repo: wordpress
        reference: latest
  creds:
    - cloud
    - git